### ISSUE TITLE
Source Information of testcases

### ISSUE THREAD

**Issue by cmkhaledsaifullah** [DeepTyper/DeepTyper#6]
First of all, I like to thank you for such inspiring work which helps me to formulate my research. I ran your training and inferring scripts and got result on the gold-dataset. If i am not wrong these are columns at evaluation-true.txt file:
**True Type**: The actual label of the test case.
**CheckJS' Type Guess**: The type predicted by CheckJS (Default type infer engine of TypeScript)
**DeepTyper's type guess**: The type predicted by DeepTyper
**DeepTyper's confidence**: How much confidence is DeepTyper. Basically the output probability of the type predicted by DeepTyper
**DeepTyper's "rank"**: The position of the prediction in the top-k recommendation list. MRR can be calculated using this value.

To do an analysis I need to have the source position information of each test case which includes file name, variable/function/return statement position.

Can you walk through me the edition of your source code that can output such information along with above 5 for each test case at evaluation-true.txt?

Thanks again for your time and effort.

**Comment by VHellendoorn** [comment]
Hi,

Thanks for reaching out! That does seem like worthwhile information, but I'm afraid it will take a bit of work to get that information out. My main recommendation would be to extract this in the AST-walking procedure that actually finds (and removes) the type annotations to begin with. Using the AST should allow you to record where the types were located in terms of its contextual AST nodes, e.g. the surrounding function, class, and statement. In addition, I'm almost certain that the TypeScript parser can tell you the line-number and character position for any AST node (since virtually all parsers support this).

If you want to go this route, the main source of this logic can be found in `CleanRepos.js`, which creates two file types for each source file (`.ttokens`, which stores every inferred type, and `.ttokens.pure`, which stores only the actual annotations). I'm afraid it's not the cleanest code (I have an updated version locally that is work-in-progress), but the main function of interest would be the `extractTokens` function at line 97, which recursively walks the AST and extracts types from any applicable leaf. Adding some maps/lists to track actual position for each type that is stored should be fairly doable from there.

I can't think of any obvious alternatives that are also watertight. If you're happy with an approximate alternative, I bet you could get a long way by just counting the number of occurrences of an identifier in the raw text of the file and comparing that with the type annotation sites. But you're bound to run into some alignment issues (e.g. with identifiers in strings), so I'd prefer the AST-based approach.

Hope this helps!

**Comment by cmkhaledsaifullah** [comment]
Thank you very much for the comment. I found a way to extract source code position and yes it worked when I use AST-based approach. in extractTokens function, along with the annotation, I save the position in a list and later in a file same name as the js or ts script file. In training, I need not use the position file and in testing, I simply match the annotations in the .ttokens.pure file and got what I was looking for.  Your comment was very helpful and Thanks again.
