### ISSUE TITLE
Web-API

### ISSUE THREAD

**Issue by FeldiPat** [DeepTyper/DeepTyper#8]
Hi,
I stumbled across your paper and would love to try out the Web API.
However, as far as I can see it is not present in the repository.
Are there any chances to try it out as shown in the paper?

Thanks in advance,
Patric

**Comment by VHellendoorn** [comment]
Hi Patric,

Thanks for reaching out! We indeed didn't include the website in this repo, mostly for space reasons (the whole VS Solution with models and dependencies is about 1GB). The original goal was to host it online through Microsoft research, but I guess we never got around to that.

I've dug up the original source code and will see if I can compress it into something more reasonable to release it. While I do that, could you indicate how important this is to you? I ask because it might be easiest for me to send you the VS project directly so you can run it locally -- I'm not sure if I'll be able to host this any time soon, or get it down to a small package. Another option is for me to just release the HTML+JS that takes the file produced by `pretrained/readout.py` and renders the corresponding website -- that's pretty much what happens internally.

-Vincent

**Comment by FeldiPat** [comment]
Hi Vincent,

Yeah I followed the path you basically proposed in your answer and adapted the readout.py script for my purposes.
Therefore, it's perfectly fine for me now.

Thank you very much for you answer,
Patric
